feat: создать структуру приложения и настроить работу User и Item
FisanovE/java-shareit pull request #1
Opened 2023-10-29 17:40 UTC by FisanovE

2023-10-30 05:40 UTC, krylov-sergey-sergeevich requested changes
Привет, давай доработаем мелочи

Хочу добавить такую практику, в реальной жизни в PR идет краткое описание того что было реализовано. Давай попробуем ввести ее и тут, нужно описать всю домашку парой фраз/предложений.

2023-10-30 05:40 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/ValidateService.java
Какие то методы начинаются с check какие то с checking - нужно однообразие ибо возникает вопрос, а есть разница?

2023-10-30 05:40 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-10-30 05:40 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +    public UserStorageImpl(UserMapper mapper, @Lazy ItemStorage itemStorage) {
Lazy - это нехорошая практика показывающая что идет проблема с проектированием классов, нельзя ли разложить логику на несколько классов чтобы не требовалось Lazy  использовать?

2023-10-30 15:28 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/ValidateService.java
Исправлено.

2023-10-30 15:35 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                          @RequestHeader("X-Sharer-User-Id") Long userId) {
Выполнено.

2023-10-30 15:51 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +    public UserStorageImpl(UserMapper mapper, @Lazy ItemStorage itemStorage) {
Исправлено. Проверка наличия User перенесена из ItemStorageImpl в ItemService, зависимость в ItemStorageImpl от UserStorage ликвидирована, тем самым циклическая зависимость устранена.

2023-10-31 09:47 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-10-31 18:38 UTC, merged