Add bookings
FisanovE/java-shareit pull request #2
Opened 2023-11-19 10:36 UTC by FisanovE

Добавлены функции бронирования вещей и добавления отзывов. Созданы сущности Booking и Comment и классы для работы с ними. Подключены БД Н2 и PostgreSQL. Реализовано хранение данных в БД. Изменена логика ранее созданных классов для работы с новыми сущностями и БД.

2023-11-20 05:27 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но мелкие правки давай внесем.

Можно почитать про @JsonFormat

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String headerUserId = "X-Sharer-User-Id";
лучше вынести в константы всего приложения, а не класса

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +@RequiredArgsConstructor
Лишние аннотации лучше не накидывать

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +    WAITING, APPROVED, REJECTED, CANCELED;
лучше делать по 1 значению в 1 строку

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private LocalDateTime created;
Можно вот так: private LocalDateTime created = LocalDateTime.now();

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/CommentMapper.java
> +@Slf4j
Лишние аннотации

2023-11-20 05:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String description;
@Column(name = "description", length = 4000) - размер тут указать было бы кстати

2023-11-20 14:36 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +    WAITING, APPROVED, REJECTED, CANCELED;
Исправлено.

2023-11-20 14:39 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private LocalDateTime created;
Выполнено.

2023-11-20 15:42 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/booking/model/BookingMapper.java
> +@RequiredArgsConstructor
Исправлено.

2023-11-20 15:42 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/item/model/CommentMapper.java
> +@Slf4j
Исправлено.

2023-11-20 15:50 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>      private String description;
Выполнено.

2023-11-21 08:11 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String headerUserId = "X-Sharer-User-Id";
Выполнено.

2023-11-22 14:04 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-11-22 14:04 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/common/Constants.java
> +@Component
Тут это излишне, пусть будет обычным классом

2023-11-22 14:04 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/common/Constants.java
> +    public static final String headerUserId = "X-Sharer-User-Id";
константные переменные по code style лучше называть в стиле CAPS_LOCK

2023-11-23 14:50 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/common/Constants.java
> +@Component
Исправлено.

2023-11-23 14:50 UTC, FisanovE commented on src/main/java/ru/practicum/shareit/common/Constants.java
> +    public static final String headerUserId = "X-Sharer-User-Id";
Исправлено.

2023-11-23 15:05 UTC, merged